In [1]:
import pandas as pd
from pathlib import Path
import json

data_file = Path("tmdb_data_1950_2024.json")
data = json.loads(data_file.read_text())

In [2]:
year_dfs = list()
for k, v in data.items():
    tmp_df = pd.DataFrame(v)
    tmp_df["year"] = k
    year_dfs.append(tmp_df)

In [3]:
df = pd.concat(year_dfs)
df = df[df["vote_count"] > 2000]

In [4]:
assert len(df[df["adult"] == True]) == 0

In [5]:
df.drop(columns=["adult"], inplace=True)

In [6]:
df.head()

,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,year
0,/rH0DPF7pB35jxLxKb3JRUgCrrnp.jpg,"[10751, 14, 16, 10749]",11224,en,Cinderella,Cinderella has faith her dreams of a better li...,100.819,/avz6S9HYWs4O8Oe4PenBFNX4uDi.jpg,1950-02-22,Cinderella,False,7.044,6523,1950
1,/p47ihFj4A7EpBjmPHdTj4ipyq1S.jpg,[18],599,en,Sunset Boulevard,A hack screenwriter writes a screenplay for a ...,57.740,/sC4Dpmn87oz9AuxZ15Lmip0Ftgr.jpg,1950-08-10,Sunset Boulevard,False,8.312,2485,1950
11,/zyO6j74DKMWfp5snWg6Hwo0T3Mz.jpg,"[80, 18, 9648]",548,ja,羅生門,Brimming with action while incisively examinin...,21.011,/vL7Xw04nFMHwnvXRFCmYYAzMUvY.jpg,1950-08-26,Rashomon,False,8.091,2121,1950
0,/b4yiLlIFuiULuuLTxT0Pt1QyT6J.jpg,"[16, 10751, 14, 12]",12092,en,Alice in Wonderland,"On a golden afternoon, young Alice follows a W...",75.465,/20cvfwfaFqNbe9Fc3VEHJuPRxmn.jpg,1951-07-28,Alice in Wonderland,False,7.200,5697,1951
0,/mxf8hJJkHTCqZP3m4o8E1TtwHHs.jpg,"[35, 10749]",872,en,Singin' in the Rain,"In 1927 Hollywood, a silent film production co...",31.407,/w03EiJVHP8Un77boQeE7hg9DVdU.jpg,1952-04-09,Singin' in the Rain,False,8.200,3036,1952

In [7]:
df.to_csv("movies.csv", index=False)

In [8]:
df.sort_values("vote_count", ascending=False).head(10)

,backdrop_path,genre_ids,id,original_language,original_title,overview,popularity,poster_path,release_date,title,video,vote_average,vote_count,year
1,/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg,"[28, 878, 12]",27205,en,Inception,"Cobb, a skilled thief who commits corporate es...",235.098,/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg,2010-07-15,Inception,False,8.368,35918,2010
0,/xJHokMbljvjADYdit5fK5VQsXEG.jpg,"[12, 18, 878]",157336,en,Interstellar,The adventures of a group of explorers who mak...,283.624,/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg,2014-11-05,Interstellar,False,8.436,34594,2014
3,/dqK9Hag1054tghRQSqLSfrkvQnA.jpg,"[18, 28, 80, 53]",155,en,The Dark Knight,Batman raises the stakes in his war on crime. ...,112.129,/qJ2tW6WMUDux911r6m7haRef0WH.jpg,2008-07-16,The Dark Knight,False,8.516,32120,2008
3,/vL5LR6WdxWPjLPFRLe133jXWsh5.jpg,"[28, 12, 14, 878]",19995,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",128.898,/kyeqWdyUXW608qlYkRqosgbbJyK.jpg,2009-12-15,Avatar,False,7.582,30979,2009
4,/9BBTo63ANSmhC4e6r62OJFuK2GL.jpg,"[878, 28, 12]",24428,en,The Avengers,When an unexpected enemy emerges and threatens...,172.761,/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg,2012-04-25,The Avengers,False,7.714,30162,2012
1,/en971MEXui9diirXlogOrPKmsEn.jpg,"[28, 12, 35]",293660,en,Deadpool,The origin story of former Special Forces oper...,299.745,/3E53WEZJqP6aM84D8CckXx4pIHw.jpg,2016-02-09,Deadpool,False,7.614,30057,2016
4,/mDfJG3LC3Dqb67AZ52x3Z0jU0uB.jpg,"[12, 28, 878]",299536,en,Avengers: Infinity War,As the Avengers and their allies have continue...,240.754,/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg,2018-04-25,Avengers: Infinity War,False,8.246,29039,2018
1,/hZkgoQYus5vegHoetLkCJzb17zJ.jpg,[18],550,en,Fight Club,A ticking-time-bomb insomniac and a slippery s...,135.882,/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg,1999-10-15,Fight Club,False,8.440,28703,1999
0,/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg,"[53, 80]",680,en,Pulp Fiction,"A burger-loving hit man, his philosophical par...",261.651,/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg,1994-09-10,Pulp Fiction,False,8.488,27273,1994
2,/mzfx54nfDPTUXZOG48u4LaEheDy.jpg,"[35, 18, 10749]",13,en,Forrest Gump,A man with a low IQ has accomplished great thi...,159.372,/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg,1994-06-23,Forrest Gump,False,8.475,26790,1994